### ISSUE TITLE
Error removing doc from pdf collection

### ISSUE THREAD

**Issue by ChaseJ** [jgdovin/meteor-html-pdf#3]
Once you remove the insecure package, you will get an error when trying to remove the pdf doc from PdfCollection.

I believe you just need to add an allow permission to index.js

I solved the problem with the following code:

```
PdfCollection.allow({
    remove: function (userId, doc) {
        return true;
    }
});
```

**Comment by jgdovin** [comment]
ah minor oversight, thank you for catching this. I will add this when I get home this evening.

**Comment by jgdovin** [comment]
latest commit should fix this. Also pushed to atmosphere.
