### ISSUE TITLE
remove failed: Access denied undefined

### ISSUE THREAD

**Issue by rico** [jgdovin/meteor-html-pdf#7]
Thank you very much for the package - simple to use, works like a charm.

I noticed the following error in my (Browser) console: `remove failed: Access denied undefined` using the `Meteor.pdf.save()` method. However, the code works fine.

I added the following allow / deny rules ...

``` javascript
if( Meteor.isServer ) {
  PdfCollection.allow({
    insert: function () {
      return true;
    },
    remove: function () {
      return true;
    },
    update: function () {
      return false;
    }
  });
}
```

... and the error was gone. May very well be a misuse on my side. Just wanted to let you know.

**Comment by ChaseJ** [comment]
Are you using the latest version of the package?

I had the same [issue](https://github.com/jgdovin/meteor-html-pdf/issues/3). The error was fixed with the [last commit](https://github.com/jgdovin/meteor-html-pdf/commit/f11fda52300562bf2f819e8a06516e75f7166318).

**Comment by rico** [comment]
You are right - the package update was not applied unless I stopped the app. Everything ok now. 

I didn't find you issues cause I was searching for access denied / remove failed.
